const ACCEPTABLE_CONTRAST_AA = 4.5;
const ACCEPTABLE_CONTRAST_AAA = 7;
const LARGE_SCALE_CONTRAST_AA = 3.1;
const LARGE_SCALE_CONTRAST_AAA = 4.5;
const LARGE_FONT_WITH_BOLD_INDEX = 18.5;
const LARGE_FONT_INDEX = 24;
const HEX_REGEX = new RegExp(/^#[0-9A-F]{3,6}[0-9a-f]{0,2}$/i);

export {
  ACCEPTABLE_CONTRAST_AA,
  ACCEPTABLE_CONTRAST_AAA,
  LARGE_SCALE_CONTRAST_AA,
  LARGE_SCALE_CONTRAST_AAA,
  LARGE_FONT_WITH_BOLD_INDEX,
  LARGE_FONT_INDEX,
  HEX_REGEX
};
